CREATE TABLE FOOD_SPOT
(
    FOOD_SPOT_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
    STORE_NAME VARCHAR(255) NULL,
    CONTENT VARCHAR(255) NULL,
    PHONE VARCHAR(255) NULL,
    ZIP_CODE VARCHAR(255) NULL,
    ADDRESS_LINE1 VARCHAR(255) NULL,
    ADDRESS_LINE2 VARCHAR(255) NULL,
    OPERATING_HOURS VARCHAR(255) NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL

);