CREATE TABLE RECIPE_IMG
(
    RECIPE_IMG_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
    RECIPE_NO BIGINT NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL,
    FOREIGN KEY (RECIPE_NO) REFERENCES RECIPE (RECIPE_NO)

);