CREATE TABLE STICKER
(
    STICKER_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
    STICKER_URL VARCHAR(255) NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL

);