CREATE TABLE MEMBER
(
    MEMBER_NO BINARY(16) PRIMARY KEY,
    LOGIN_ID VARCHAR(255) NULL,
    EMAIL VARCHAR(255) NULL,
    PASSWORD VARCHAR(255) NULL,
    ROLES VARCHAR(255) NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL
);