CREATE TABLE IMAGE_STICKERS
(
    IMAGE_STICKERS_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
    RECIPE_IMG_NO BIGINT NULL,
    STICKER_NO BIGINT NULL,
    METADATA JSON NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL,
    FOREIGN KEY (RECIPE_IMG_NO) REFERENCES RECIPE_IMG (RECIPE_IMG_NO),
    FOREIGN KEY (STICKER_NO) REFERENCES STICKER (STICKER_NO)

);