CREATE TABLE RECIPE
(
    RECIPE_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
    FOOD_NAME VARCHAR(255) NULL,
    INSTRUCTIONS VARCHAR(255) NULL,
    INGREDIENTS VARCHAR(255) NULL,
    CATEGORY VARCHAR(255) NULL,
    AUTHOR VARCHAR(255) NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL

);