CREATE TABLE MEMBER_INFO
(
    MEMBER_INFO_NO BINARY(16) PRIMARY KEY,
    MEMBER_NO BINARY(16) NULL,
    NICKNAME VARCHAR(255) NULL,
    PHONE VARCHAR(255) NULL,
    ZIP_CODE VARCHAR(255) NULL,
    ADDRESS_LINE1 VARCHAR(255) NULL,
    ADDRESS_LINE2 VARCHAR(255) NULL,
    STATUS VARCHAR(255) NULL,
    CREATE_AT TIMESTAMP NULL,
    UPDATE_AT TIMESTAMP NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)

);